name: Test Documentation
on:
  pull_request:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yml@master
    with:
      skip_doxygen: true
      dependencies: cmake sphinx
